version: '3.8'
services:
  vector_pg:
    container_name: vector_pg
    image: ankane/pgvector
    restart: always
    networks:
      - localnetwork
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes: 
      - vector_pg:/var/lib/postgresql/data

networks:
  localnetwork:

volumes:
  vector_pg:
    driver: local