version: '3.8'
services:
  vector_pg:
    container_name: vector_pg
    image: ankane/pgvector
    restart: always
    networks:
      - localnetwork
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes: 
      - vector_pg:/var/lib/postgresql/data
  
  neo4j:
    container_name: neo4j
    image: neo4j:latest
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/12345
      # - NEO4J_AUTH:none
    volumes:
      - neo4j:$HOME/neo4j/data:/data
      - neo4j:$HOME/neo4j/logs:/logs
      - neo4j:$HOME/neo4j/import:/import
      - neo4j:$HOME/neo4j/plugins:/plugins

networks:
  localnetwork:

volumes:
  vector_pg:
    driver: local
  neo4j:
    driver: local